# Generated by Django 4.0 on 2021-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefmodel',
            name='ProfileImage',
            field=models.FileField(default='None', max_length=600, upload_to='Chief/ChiefProfile/'),
        ),
    ]
