# Generated by Django 4.0 on 2021-12-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0002_alter_chiefmodel_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('userid', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordsManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.CharField(default='table', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('TotalCost', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=800)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=300)),
                ('itemCost', models.CharField(max_length=300)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
    ]
