# Generated by Django 4.0 on 2021-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0003_customerbill_recordsmanger_homedelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='quantity',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
