# Generated by Django 4.0 on 2021-12-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0004_customeritems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='orginalCost',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
