# Generated by Django 4.0 on 2022-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0007_remove_chiefmodel_id_alter_chiefmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsmanger',
            name='active',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
