# Generated by Django 4.0 on 2021-12-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0002_sweetcornermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockname', models.CharField(max_length=300)),
                ('BannerOfdata', models.CharField(max_length=300)),
                ('BannerImage', models.FileField(max_length=600, upload_to='Beverages/')),
            ],
        ),
    ]
