# Generated by Django 4.0 on 2021-12-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0003_cusdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdashboard',
            name='BannerImage',
            field=models.FileField(max_length=600, upload_to='DashboardBanner/'),
        ),
    ]
