# Generated by Django 4.0 on 2021-12-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0005_auto_20211214_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('Caregories', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=300)),
                ('Dishcost', models.CharField(max_length=300)),
                ('Check', models.CharField(default='veg', max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.menucategories')),
            ],
        ),
    ]
