# Generated by Django 4.0 on 2021-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0006_menucategories_starter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starter',
            old_name='DishName',
            new_name='StarterName',
        ),
        migrations.RenameField(
            model_name='starter',
            old_name='Dishcost',
            new_name='Startercost',
        ),
        migrations.AddField(
            model_name='starter',
            name='Starter',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='starter',
            name='starterIamge',
            field=models.FileField(default='None', max_length=600, upload_to='Mainmenu/Starter/'),
        ),
    ]
