# Generated by Django 4.0 on 2021-12-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0007_rename_dishname_starter_startername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_CourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaincourceName', models.CharField(max_length=300)),
                ('MaincourceCost', models.CharField(max_length=300)),
                ('MaincourceIamge', models.FileField(max_length=600, upload_to='Mainmenu/MainCource/')),
                ('Check', models.CharField(default='veg', max_length=100)),
                ('Maincource', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.menucategories')),
            ],
        ),
    ]
