# Generated by Django 4.0 on 2021-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0008_main_courcemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceChapati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.CharField(default='veg', max_length=100)),
            ],
        ),
    ]
