# Generated by Django 4.0 on 2021-12-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0010_ricechapati_createddate_ricechapati_itemcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese_Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=300)),
                ('ItemCost', models.CharField(max_length=100)),
                ('ItemImage', models.FileField(default='None', max_length=600, upload_to='Mainmenu/Chinese_Snacks/')),
                ('Check', models.CharField(default='snacks', max_length=100)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
