# Generated by Django 4.0 on 2021-12-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0011_chinese_snacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinese_snacks',
            name='ItemImage',
            field=models.FileField(default='None', max_length=600, upload_to='Chinese_Snacks/'),
        ),
    ]
