# Generated by Django 4.0 on 2022-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheiffood',
            name='userid',
            field=models.CharField(default='table', max_length=20),
        ),
    ]
